version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: dashboard-ac-postgres
    environment:
      POSTGRES_USER: 4dm1n
      POSTGRES_PASSWORD: 4dm1nP@ssw0rd
      POSTGRES_DB: dashboard_ac_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - dashboard-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Service
  api:
    build: .
    container_name: dashboard-ac-api
    env_file:
      - .env.docker
    ports:
      - "8088:8088"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - dashboard-network
    restart: always
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data:

networks:
  dashboard-network:
    driver: bridge